### ISSUE TITLE
can you add a new option for http proxy? This tool can not run in inner netwok need to set proxy to access internet.

### ISSUE THREAD

**Issue by tuhaolam** [illikainen/ossaudit#2]

**Comment by SVilgelm** [comment]
Have you tried?
```bash
export http_proxy=http://SERVER:PORT/
```

**Comment by illikainen** [comment]
The underlying library used for network requests is [requests](https://requests.readthedocs.io).  As suggested by @SVilgelm, it seems to obey the standard HTTP_PROXY and HTTPS_PROXY environment variables for proxy configuration.

I'm not sure how `requests` handles proxy configurations on non-*nix OS:es.  I'm open to implementing proxy support if somebody (@tuhaolam ?) makes an argument for where it makes sense.

**Comment by tuhaolam** [comment]
> Have you tried?
> 
> ```shell
> export http_proxy=http://SERVER:PORT/
> ```

thanks, it works.

**Comment by tuhaolam** [comment]
> The underlying library used for network requests is [requests](https://requests.readthedocs.io). As suggested by @SVilgelm, it seems to obey the standard HTTP_PROXY and HTTPS_PROXY environment variables for proxy configuration.
> 
> I'm not sure how `requests` handles proxy configurations on non-*nix OS:es. I'm open to implementing proxy support if somebody (@tuhaolam ?) makes an argument for where it makes sense.

`export http_proxy=http://SERVER:PORT/`, it works. Thanks a lot.
